#!/bin/bash
# 2019-08-25
# scf : set console font

if 	[[ -z $DISPLAY ]]; then
	while true
 		do read -r -n 1 -p " Proceed with a larger default font?       yes/no
"		-s yn || { echo && exit; }
			echo
			case $yn in
				y|yes) 	setfont LatGrkCyr-12x22.psfu.gz ; echo " Searching fonts...." ; break	;;
				n|no)   echo " Searching fonts...." ; echo ;				break	;;
				* ) echo "y-n ?"								;;
			esac
		done

	if	! pacman -Qq terminus-font &>/dev/null ; then
		while true
			do read -r -n 1 -p " Want to install terminus fonts?       yes/no
"			-s yn || { echo && exit; }
				case $yn in
					y|yes) { if	[[ $(whoami) == root && $(hostname) == archiso && ! -d /var/lib/pacman/sync/ ]]; then
							echo; echo " Seems you're running a live Arch iso" 
							echo " and the pacman sync database does not exist."
							echo " Creating sync database...."
							pacman -Sy &>/dev/null; echo
						fi } ; sudo pacman -S terminus-font --needed ;	break	;;
					n|no)			  				break	;;
					* ) echo "y-n ?"						;;
				esac
			done
	    else
		echo " terminus-font already installed." ; echo
		sleep 2
	fi
fi
	readarray -t available <<< "$(find /usr/share/kbd/consolefonts  -type f -name "*.psf*.gz" -printf '%f\n' 2>/dev/null | sort -u)"

	printf "%s\n" "${available[@]}" | nl -v 0 -w3 -s, --number-separator=' = ' | column

	echo; echo " Select a number between 0 and $(( ${#available[@]} - 1 )). [Shift]+[Page Up]/[Page Down] to scroll."
	echo

	read -r font

	echo

amount=$(( "${#available[@]}" - 1))

if	[[ ${font} =~ [0-9] ]] && (( "$font" >= 0 && "$font" <= "${amount}" )); then

	echo " Selected: ${font} = ${available[$font]}."
	echo

	if	[[ -n $DISPLAY ]]; then 
		echo " Scf runs only in a virtual console, ie: tty[N]. Cannot run in a \"terminal emulator\" within X. (exit 1)"
		echo 
		exit 1 
	fi

	setfont "${available[${font}]}"

	else

	echo " \"${font}\" is not a number between 0 and $(( ${#available[@]} - 1 ))! (exit 1)"
	echo

	exit 1
fi
